### ISSUE TITLE
StatusCode 401

### ISSUE THREAD

**Issue by manshurtigh** [bureus/MMM-Vasttrafik-PublicTransport#25]
Hi!

It seems to me that I cannot connect to Västtrafik. I was wondering if anyone has seen this problem before? See logs belows. 

```
[27.07.2023 17:55.31.923] [LOG]   5:55:31 PM MMM-Vasttrafik-PublicTransport: generateAccessToken failed =StatusCodeError: 401 - ""
[27.07.2023 17:55.31.932] [WARN]  Unhandled rejection ReferenceError: reject is not defined
    at /opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_helper.js:78:11
    at tryCatcher (/opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/opt/magic_mirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
```

401 indicates that I have an authorization issue, but I can't figure out what's wrong. I've checked the APIs that the application is subscribed to. See below image.

![2023-07-27 18_06_58-Västtrafik - Developer portal - My applications](https://github.com/bureus/MMM-Vasttrafik-PublicTransport/assets/11875063/89ea8386-9568-4593-af0a-7e822011f267)

I am using ClientID as "appKey" and Secret as "appSecret". 

```
appKey: "yyyyyy",
appSecret: "xxxxxxxxxx",
```

Am I doing something wrong?

**Comment by Xkhi** [comment]
I had similar issues with this module, what I noticed is that it relies on v2 of Västtrafik's API, I made a fork to update it to v4 and merge some other forks to support multi-filtering. Feel free to check the other forks
https://github.com/bureus/MMM-Vasttrafik-PublicTransport/network/members

**Comment by manshurtigh** [comment]
Yeah, I saw that this one relies on v2 as well and I thought it had something to do with that as well.

Thank you for creating a fork and updating it to v4. I actually started to use MMM-ResRobot instead in the mean time. I will try your fork.

**Comment by manshurtigh** [comment]
Your fork worked perfectly! Thank you so much @Xkhi. 

I suggest that you actually put this up as a separate "version 2" or something similar on the 3rd module pages here on Github so more people can find this.

I leave this comment open so more people may find it since the authentication is a crucial part of the module to work. Again, thank you so much @Xkhi.

**Comment by Xkhi** [comment]
I thought of doing that, but it felt wrong... but now that you suggest it, I'll do it. Thanks for the encouragement.

**Comment by manshurtigh** [comment]
Do it! I don't think @bureus supports this module anymore.

**Comment by manshurtigh** [comment]
@Xkhi Could you add me on Discord? My name is snåm#8165. I have some more ideas for this module, if you are interested.

**Comment by Xkhi** [comment]
I don't use discord that much, but sure, we can discuss in private

**Comment by Bagronk** [comment]
Hi, I just thought I'd check with you. The only thing that shows up on my MagicMirror is the Västtrafik logo. What could be wrong? I setup a mirror in 2018 or something and that has worked until now when the SD-card in the Pi died, and I can't find the backup. So now I have a Linux Mint based Mirror. I got the API to the weather module to work but not this one.

**Comment by Xkhi** [comment]
this library is super outdated, I would recommend to use one of the forks that stem from it

**Comment by Bagronk** [comment]
Oh, I am. I was just a bit tired and commented here. I'm using your fork.

**Comment by kallby86** [comment]
I also only get the Västtrafik Logo and i have updated to your fork? @Bagronk did you get it to work?

**Comment by Bagronk** [comment]
I got it working, and it is working. But I can't remember what I did. It does however give me errors in the terminal when running the mirror. 

Are you using xkhi's fork?

**Comment by Bagronk** [comment]
Actually! Check the brackets one by one. I have a vague memory of something being off with the brackets.

**Comment by kallby86** [comment]
Yes i am using xkhi's fork. Then i have alot of work to do, i am not a programmer either so i don't understand the brackets very well

**Comment by kallby86** [comment]
[23.01.2024 00:03.58.287] [LOG]   00:03:58 MMM-Vasttrafik-PublicTransport: generateAccessToken failed =StatusCodeError: 401 - "{\"error_description\":\"Client Authentication failed.\",\"error\":\"invalid_client\"}"
[23.01.2024 00:03.58.304] [WARN]  Unhandled rejection ReferenceError: reject is not defined
    at /home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_helper.js:78:11
    at tryCatcher (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

**Comment by Bagronk** [comment]
I'm not that good at this either but it seems like the token and client
doesn't work.

Have you gone to the developer site, created account and created
application?

Den tis 23 jan. 2024 00:06kallby86 ***@***.***> skrev:

**Comment by Zoonie81** [comment]
@Xkhi thanks for updating and forking this! I'm seeing some issues compared to the master, not sure why.
* Upcoming departures column is always empty
* Using multiple stops, the second stop only shows 1-2 lines at most

I've checked API v4 console and the info is there, it just doesn't output properly in this module. Do you have the same issues?

**Comment by Xkhi** [comment]
Hi guys, I have enabled issues in my fork, you can go ahead and move the conversation there
